apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ruby-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-ruby-app
  template:
    metadata:
      labels:
        app: my-ruby-app
    spec:
      containers:
        - name: my-ruby-app
          image: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_AWS_REGION>.amazonaws.com/my-ruby-app:latest
          ports:
            - containerPort: 4567
